#!/bin/bash

FLAGS="--tty --rm"

if [ $# -eq 0 ] ; then
  FLAGS+=" --interactive"
fi

# shellcheck disable=SC2086
# shellcheck disable=SC2048
docker run -v "$(pwd)":/home/si-user $FLAGS super-image:dev $*